# Generated by Django 2.2.3 on 2019-07-28 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20190728_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 8, 46, 57, 626392), verbose_name='date published'),
        ),
    ]
