# Generated by Django 2.2.3 on 2019-07-28 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20190728_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='catetory_slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='catetory_summary',
            new_name='category_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 10, 38, 53, 255562), verbose_name='date published'),
        ),
    ]
