# Generated by Django 2.2.3 on 2019-07-28 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20190728_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 15, 35, 8, 87471), verbose_name='date published'),
        ),
    ]
